# app_pages/page_cancellation.py

import streamlit as st
import pandas as pd

from src import data_loaders, models, features
from src.ui import inject_global_css


def _get_calendar_row_for_date(tour_date: pd.Timestamp):
    weekly = data_loaders.load_weekly_regression_data()
    week_start = tour_date - pd.to_timedelta(tour_date.weekday(), unit="D")
    row = weekly[weekly["week_start"] == week_start].iloc[0]
    return row


def app():
    inject_global_css()

    st.title("⚠️ Cancellation Risk")

    st.markdown(
        """
        <div class="card">
        Estimate <strong>cancellation risk</strong> for a single upcoming booking using the
        trained classification model. The result is a probability and a high/low risk flag
        based on your chosen threshold.
        </div>
        """,
        unsafe_allow_html=True,
    )

    with st.form("cancellation_form"):
        col1, col2 = st.columns(2)

        weekly = data_loaders.load_weekly_regression_data()
        regions = sorted(weekly["region"].unique())

        with col1:
            region = st.selectbox("Region", options=regions)
            tour_date = st.date_input("Tour date")
            party_size = st.slider("Party size", min_value=1, max_value=10, value=3)
            lead_time_days = st.slider(
                "Lead time (days between booking and tour)",
                min_value=1,
                max_value=90,
                value=21,
            )

        with col2:
            route_difficulty = st.selectbox(
                "Route difficulty",
                options=["easy", "moderate", "challenging"],
                index=1,
            )
            weather_severity_bin = st.selectbox(
                "Expected weather severity",
                options=["mild", "moderate", "severe"],
                index=1,
            )
            threshold = st.slider(
                "High-risk threshold (probability)",
                min_value=0.1,
                max_value=0.9,
                value=0.5,
                step=0.05,
            )

        submitted = st.form_submit_button("Estimate risk")

    if not submitted:
        st.info("Fill in the booking details and click **Estimate risk**.")
        st.info("""
            **Model Performance (LO4.2):**  
This cancellation probability is generated by the tuned XGBoost classifier, which achieved:  
- ROC AUC ≈ **0.628**

This indicates moderate predictive ability, above random classification.  
The model **meets the requirement** of providing a functional prototype for risk identification.
""")

        return

    tour_dt = pd.to_datetime(tour_date)
    calendar_row = _get_calendar_row_for_date(tour_dt)

    booking_features = features.build_classification_feature_dict(
        region=region,
        route_difficulty=route_difficulty,
        weather_severity_bin=weather_severity_bin,
        party_size=party_size,
        lead_time_days=lead_time_days,
        tour_date=tour_dt,
        calendar_row=calendar_row,
    )

    result = models.predict_cancellation_risk(
        booking_features=booking_features, threshold=threshold
    )

    prob = result["probability"]
    is_high_risk = result["is_high_risk"]

    st.subheader("Prediction")

    col_left, col_right = st.columns(2)
    with col_left:
        st.metric(
            label="Predicted cancellation probability",
            value=f"{prob:.1%}",
        )

    with col_right:
        st.metric(
            label="High-risk?",
            value="Yes" if is_high_risk else "No",
        )

    with st.expander("Features used for this prediction"):
        st.json(booking_features)

    st.markdown(
        """
        - Lower thresholds (e.g. 0.4) will flag more bookings as high-risk (higher recall but more false positives).  
        - Higher thresholds (e.g. 0.7) will only flag the most likely cancellations (lower recall, fewer false positives).  
        """
    )


